# Clase 1: Introducción a Numpy, Pandas y Matplotlib #

## Numpy

In [2]:
import numpy as np # Acrónimo reconocido de Numpy
print(np.__version__)

1.19.2


### Creación de ndarrays ###

Un ndarray es un array de n dimensiones. Asemeja una matriz en Álgebra Lineal. Para definir la forma de una matriz, definimos primeros sus dimensiones mayores y luego sus dimensiones menores.

In [13]:
# Se puede crear...
lista = [2, 5, 8, 9, 0]
# a través de una lista de Python
lista_nd = np.array(lista)
# rellenándolo con un valor en especial
ceros, unos, vacios, rellenos = np.zeros((2, 3)), np.ones((2, 4)), np.empty((3, 2)), np.full((4, 3), 5)
# de un intervalo
intervalo = np.arange(1, 12)
# de forma aleatoria
random = np.random.rand(2, 3)

In [16]:
lista_nd

array([2, 5, 8, 9, 0])

In [17]:
ceros, unos, vacios, rellenos

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]))

In [18]:
intervalo, random

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[0.34226043, 0.6889392 , 0.21997658],
        [0.77615545, 0.76945297, 0.71146841]]))

In [28]:
# o de forma personalizada
custom_2d = np.array([[2, 3, 4], [5, 6, 7]])
custom_3d = np.array([[[3, 4, 3], [5, 3, 6]], [[2, 8, 3], [7, 4, 6]]])
custom_4d = np.arange(16).reshape((2, 2, 2, 2))

Existen múltiples dimensiones en una matriz

In [68]:
custom_2d, custom_2d.shape

(array([[2, 3, 4],
        [5, 6, 7]]),
 (2, 3))

In [70]:
custom_3d, custom_3d.shape

(array([[[3, 4, 3],
         [5, 3, 6]],
 
        [[2, 8, 3],
         [7, 4, 6]]]),
 (2, 2, 3))

In [79]:
np.sum(custom_3d, axis=2)

array([[10, 14],
       [13, 17]])

In [71]:
custom_4d, custom_4d.shape

(array([[[[ 0,  1],
          [ 2,  3]],
 
         [[ 4,  5],
          [ 6,  7]]],
 
 
        [[[ 8,  9],
          [10, 11]],
 
         [[12, 13],
          [14, 15]]]]),
 (2, 2, 2, 2))

### Manipulando ndarrays ###

Las selección de elementos en un array es tan fácil como seleccionar coordenadas. De forma similar que en la creación de arrays o en la función reshape, elegimos desde las dimensiones mayores hasta las menores

In [35]:
# coordenada mayor, ... , coordenada menor
# Hay dos formas de hacerlo
custom_2d[1][2], custom_2d[1,2]

(7, 7)

In [37]:
# La selección no se limita a números escalares
custom_3d[1]

array([[2, 8, 3],
       [7, 4, 6]])

In [50]:
# También se pueden seleccionar segmentos personalizados
custom_4d[0,:,:,1]

array([[1, 3],
       [5, 7]])

In [52]:
# No es lo mismo esto
custom_4d[0][:][:][1]

array([[4, 5],
       [6, 7]])

### Operaciones de álgebra lineal ###

In [57]:
# Multiplicación
A = np.array([[2, 3, 7],[3, 4, 5]])
B = np.array([[3, 3],[4, 9], [2, 1]])
C = np.matmul(A, B) # Ojo, A*B es multiplicación elemento a elemento! (Element-wise)
C

array([[32, 40],
       [35, 50]])

In [59]:
# Matriz transpuesta
A, A.T

(array([[2, 3, 7],
        [3, 4, 5]]),
 array([[2, 3],
        [3, 4],
        [7, 5]]))

### Funciones universales y otros métodos ###
Las funciones universales son fucniones que viven en el contexto global de numpy y pueden aplicarse a las matrices

In [81]:
# Un simple promedio
notas = np.array([9.4, 5.6, 8.5])
np.mean(notas), np.sum(notas)/notas.shape[0]

(7.833333333333333, 7.833333333333333)

In [80]:
# Más promedios
notas_salon = np.array([[8.9, 9.1, 9.0, 9.0], [5.6, 8.7, 7.8, 4.5], [7.8, 5.6, 5.7, 8.0]])
np.mean(notas_salon, axis=1) # A lo largo del eje 1 (de mayor a menor dimensión)

array([9.   , 6.65 , 6.775])

Al seleccionar un eje, los elementos que se encuentren a lo largo de este se verán afectados por la función

Existen más métodos como max(), min(), std(), var(), etc

## Pandas ##

Todo objeto en Pandas es una instancia de Series o de DataFrame. Almacenan conjuntos de datos (files y columnas) que identifican con índices